query personList($page: Int!) {
    characters(page: $page) {
        info {
            next
        }
        results {
            id
            name
            status
            image
        }
    }
}
